export const products = [
  {
    "index": 1,
    "id": "1732052189676081387",
    "name": "[medicube] Smooth & Clear Body Care Set | Hypochlorous Acid Body Peel Shot, Kojic Acid Turmeric Body Wash, Toner Pad, Toner, Mist | Exfoliating for Dead Skin Cells & Excess Sebum & Clearing for After Spots, Texture & Uneven Skin Tone | K-Beauty",
    "category": "美妆个护 / 洗浴与身体护理 / 身体护理套装",
    "price": "$31.00",
    "image": "assets/products/001.webp",
    "short_name": "Medicube Smooth & Clear Body Care Set",
    "category_en": "Body Care Sets",
    "visual_features": "Five skincare containers arranged in a row against a white background, including a red pump bottle, an amber pump bottle, a white tub with a yellow lid, an amber bottle with a pointed nozzle, and a slim gold-capped cylinder.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 0,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 2,
    "id": "1731528580940468633",
    "name": "Nature x Science Rosemary Water and Rice Water |100% Natural Extract | Soft & Smooth Hair Non-Greasy & Fast Absorbing | 200 ml",
    "category": "美妆个护 / 头部护理与造型 / 脱发产品",
    "price": "$9.69",
    "image": "assets/products/002.webp",
    "short_name": "Nature x Science Rosemary & Rice Hair Spray",
    "category_en": "Hair Loss Products",
    "visual_features": "Clear cylindrical plastic bottle with a black trigger spray head and white label, displayed beside a sprig of fresh rosemary and a bowl of rice grains on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 1,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 3,
    "id": "1729413742968869814",
    "name": "Bella Vita Luxury's Honey Oud | Eau de Parfum 100ml (3.4 fl oz) | Patchouli, Vanilla, Bergamot | Floral & Spicy | Made with Clean & Vegan Essentials Oils | Cruelty Free Fragrance Perfume",
    "category": "美妆个护 / 香水 / 无性别香水",
    "price": "$19.99",
    "image": "assets/products/003.webp",
    "short_name": "Bella Vita Luxury Honey Oud EDP",
    "category_en": "Unisex Perfume",
    "visual_features": "Square translucent amber glass perfume bottle with gold lettering and a metallic gold cylindrical cap, casting a shadow on a white surface.",
    "profile": "style",
    "sheet": 1,
    "cell": 0,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 4,
    "id": "1729448464509734958",
    "name": "Toplux Magnesium Complex 8 Essential Magnesium Supplement",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$16.97",
    "image": "assets/products/004.webp",
    "short_name": "Toplux Magnesium Complex Supplement",
    "category_en": "Dietary Supplements",
    "visual_features": "White plastic supplement bottle with a blue and white label and ribbed screw cap, surrounded by loose white capsules, almonds, an avocado half, and a banana.",
    "profile": "active",
    "sheet": 2,
    "cell": 0,
    "confidence": 0.82,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 5,
    "id": "1729583305380172048",
    "name": "[EPAIS Official Shop] Essential Eyelash Growth Serum, Jumbo Size 0.5fl.oz - Safe & Gentle Lashes Care, Fuller, Thicker in 2 Weeks, Non-Prostaglandin, Hormone-free",
    "category": "美妆个护 / 美容护肤 / 眼部护理",
    "price": "$18.99",
    "image": "assets/products/005.webp",
    "short_name": "EPAIS Essential Eyelash Growth Serum",
    "category_en": "Eye Care",
    "visual_features": "Silver metallic cylindrical cosmetic tube standing beside an open applicator wand with a thin tip, set against a faint clear fluid smear on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 2,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 6,
    "id": "1729679758111249333",
    "name": "Loaded Tea – Single Packet | 32oz Caffeinated Flavored Hydration Powder Beverage Mix | Made in USA | Easy to Mix",
    "category": "食品饮料 / 饮料 / 冲调饮品",
    "price": "$2.45",
    "image": "assets/products/006.webp",
    "short_name": "Loaded Tea Energy Drink Mix Pouch",
    "category_en": "Drink Mixes",
    "visual_features": "Green and white checkered stand-up powder packet standing beside a clear drinking glass filled with ice and bright blue liquid.",
    "profile": "active",
    "sheet": 2,
    "cell": 1,
    "confidence": 0.95,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 7,
    "id": "1731406217255686451",
    "name": "OEAK Women Jelly Bras Wirefree Full Coverage No Underwire Everyday Bras Comfortable Wireless Padded Tshirt Bra",
    "category": "女装与女士内衣 / 女士内衣 / 女士文胸",
    "price": "$16.99",
    "image": "assets/products/007.webp",
    "short_name": "OEAK Wireless Full Coverage Jelly Bras",
    "category_en": "Women's Bras",
    "visual_features": "Two women shown from the waist up wearing wirefree full-coverage bras, one in dark charcoal brown and the other in light lilac lace.",
    "profile": "style",
    "sheet": 1,
    "cell": 1,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 8,
    "id": "1732263142232921043",
    "name": "Voyage Nova | Rosey Fruity Floral | Extrait De Parfum 50ml/100ml | Long Lasting Luxury Fragrance | Daily women's perfume Alluring Summervibes sohochic",
    "category": "美妆个护 / 香水 / 女士香水",
    "price": "$25.98",
    "image": "assets/products/008.webp",
    "short_name": "Voyage Nova Extrait De Parfum",
    "category_en": "Women's Perfume",
    "visual_features": "Clear rectangular glass perfume bottle with pale pink liquid and a glossy black fluted cap, flanked by blooming pink roses and halved lychee fruit on a white background.",
    "profile": "style",
    "sheet": 1,
    "cell": 2,
    "confidence": 0.86,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 9,
    "id": "1732560627250664403",
    "name": "QAWAFI Mystery Extrait De Parfum Gift Box, 100ml Luxury Gift Box, Long Lasting Perfumes for Unisex Wear",
    "category": "美妆个护 / 香水 / 无性别香水",
    "price": "$99.99",
    "image": "assets/products/009.webp",
    "short_name": "QAWAFI Mystery Gift Box Perfume",
    "category_en": "Unisex Perfume",
    "visual_features": "Light pink square gift box tied with a matching wide satin ribbon bow on top, featuring a hanging tag and printed label on the front.",
    "profile": "style",
    "sheet": 1,
    "cell": 3,
    "confidence": 0.93,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 10,
    "id": "1732040365570888316",
    "name": "[Sungboon] EGF Tox Toner | Forehead Firming & Wrinkle Care, Iron Out Fine Lines | PDRN & Collagen & NAD+ EGF Complex | EGF Plumping for Forehead, Longevity Anti-Aging Routine | Korean Skincare, K-Beauty",
    "category": "美妆个护 / 美容护肤 / 爽肤水、化妆水",
    "price": "$24.20",
    "image": "assets/products/010.webp",
    "short_name": "Sungboon Editor EGF Tox Toner",
    "category_en": "Toners & Mists",
    "visual_features": "Tall semi-translucent fluted cylindrical bottle with a white label and a polished gold screw cap, set beneath a yellow header banner on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 3,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 11,
    "id": "1731625997827871273",
    "name": "Bikini Pain-Free Hair Removal Cream for Sensitive Skin, Hypoallergenic Formula-Gentle & Fast-Acting Depilatory with Citrus Scent, Aloe & Hyaluronic Acid for Soothing Care, Suitable for Men & Women,backtoschool",
    "category": "美妆个护 / 洗浴与身体护理 / 除毛乳、除毛蜜蜡&除毛器",
    "price": "$16.99",
    "image": "assets/products/011.webp",
    "short_name": "Bikini Hair Removal Cream & Spray Set",
    "category_en": "Depilatory Products",
    "visual_features": "White and lavender squeeze tube standing beside a matching cylindrical spray can with a purple cap, positioned with cut aloe vera leaves and purple flowers at the base.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 4,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 12,
    "id": "1729718097057910811",
    "name": "[Dr.Melaxin Official] Calcium Dark Spot Eye Cream | Dark Circle, Anti-aging, Sagging, Elasticity | Korean Cosmetics",
    "category": "美妆个护 / 美容护肤 / 保湿乳液、乳霜与喷雾",
    "price": "$18.00",
    "image": "assets/products/012.webp",
    "short_name": "Dr.Melaxin Calcium Dark Spot Eye Cream",
    "category_en": "Eye Creams & Moisturizers",
    "visual_features": "Low round cosmetic jar with a deep purple cap and gold-toned body, topped with a dollop and curved swipe of beige cream against a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 5,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 13,
    "id": "1729687495043093429",
    "name": "Protein Loaded Coffee – Viral | Single Packet | 16oz Coffee Drink Mix | 10g Protein & 180mg Caffeine | Hot or Cold",
    "category": "食品饮料 / 饮料 / 咖啡",
    "price": "$2.50",
    "image": "assets/products/013.webp",
    "short_name": "Get Loaded Coffee Drink Mix Pouch",
    "category_en": "Coffee",
    "visual_features": "Brown kraft paper drink mix packet with a tan-and-white checkered lower section, standing beside a clear glass filled with iced, marbled coffee.",
    "profile": "home",
    "sheet": 3,
    "cell": 0,
    "confidence": 0.86,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 14,
    "id": "1732164626458252048",
    "name": "Hismile iD Stain Whitening Mouthwash for White Teeth, Freshens Breath with Essential Oils 237ml",
    "category": "美妆个护 / 鼻子口腔护理 / 漱口水",
    "price": "$14.99",
    "image": "assets/products/014.webp",
    "short_name": "Hismile iD Stain Whitening Mouthwash",
    "category_en": "Mouthwash",
    "visual_features": "Tall brushed silver metal cylinder bottle with a vibrant magenta cap, placed next to a clear round dish containing botanical elements on a white surface.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 6,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 15,
    "id": "1729505063356962201",
    "name": "Rosemary & Rice Water Hair Spray- 200ml pack of 3 Natural Soft Hair Nourishing Hair",
    "category": "美妆个护 / 头部护理与造型 / 脱发产品",
    "price": "$20.99",
    "image": "assets/products/015.webp",
    "short_name": "Rosemary & Rice Water Hair Spray 3-Pack",
    "category_en": "Hair Loss Products",
    "visual_features": "Three identical clear plastic spray bottles with black trigger heads lined in a row, featuring white botanical-illustrated labels, with rosemary and rice grains at the base.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 7,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 16,
    "id": "1729472647677055844",
    "name": "Lion Pair Acne Cream Acne Treatment Pimples Removal Cream Pair Acne Creamy Foam Facial Wash Gentle Antibacterial Blemishes Skin Repair",
    "category": "美妆个护 / 美容护肤 / 痘痘、粉刺护理",
    "price": "$6.97",
    "image": "assets/products/016.webp",
    "short_name": "Lion Pair Acne Cream",
    "category_en": "Acne & Blemish Treatments",
    "visual_features": "White and blue squeeze tube with a white cap lying in front of its matching silver and royal blue rectangular cardboard box on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 8,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 17,
    "id": "1731333919275783013",
    "name": "OANVA 2 in 1 facial & eyebrow hair trimmer for Women, Rechargeable Face Razor, Lip & Peach Fuzz Remover, Precision Eyebrow Shaper, Portable Painless Hair Removal Tool.",
    "category": "美妆个护 / 美容、个护电器 / 电动修眉刀",
    "price": "$11.99",
    "image": "assets/products/017.webp",
    "short_name": "OANVA 2-in-1 Facial & Eyebrow Trimmer",
    "category_en": "Eyebrow Trimmers",
    "visual_features": "Two rose-gold cylindrical trimmer devices standing next to a pink product box and white charging cord, with two small application photos on the right.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 9,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 18,
    "id": "1732282937141662165",
    "name": "LUCKMEEY Womens Strapless Front Closure Bra Push Up Lift Bra Padded Add Cup Non Slip  Anti-Slip Grip & Removable Straps Fit Outfits Wireless Supportive  Seamless Comfortable",
    "category": "女装与女士内衣 / 女士内衣 / 女士文胸",
    "price": "$26.18",
    "image": "assets/products/018.webp",
    "short_name": "LUCKMEEY Strapless Front Closure Bra",
    "category_en": "Women's Bras",
    "visual_features": "Two women pictured side-by-side wearing nude strapless push-up bras featuring centered front clasp closures and smooth molded cups.",
    "profile": "style",
    "sheet": 1,
    "cell": 4,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 19,
    "id": "1729718141631565851",
    "name": "[Dr.Melaxin Official] Calcium Multi Balm Eye Care Routine Korean Skin Care Anti-aging Cosmetics Collagen Eye Stick 9g",
    "category": "美妆个护 / 美容护肤 / 保湿乳液、乳霜与喷雾",
    "price": "$17.10",
    "image": "assets/products/019.webp",
    "short_name": "Dr.Melaxin Calcium Multi Balm",
    "category_en": "Eye Creams & Moisturizers",
    "visual_features": "Slender twist-up stick in plum purple and white casing, showing the exposed cream-colored stick against a matching beige swatch on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 10,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 20,
    "id": "1732574204186890998",
    "name": "Marshmallow Minis",
    "category": "美妆个护 / 洗浴与身体护理 / 身体护理套装",
    "price": "$36.00",
    "image": "assets/products/020.webp",
    "short_name": "Marshmallow Minis Skincare Set",
    "category_en": "Body Care Sets",
    "visual_features": "Miniature beauty set featuring an off-white squeeze tube, a small white dropper tube, and a clear mini bottle with an off-white cap, displayed next to a gold-trimmed box.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 11,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 21,
    "id": "1731236289885213002",
    "name": "SEESE Cordless Pressure Washer Gun, 1000 PSI Portable Electric Washer for Vehicle, Driveway & Deck - Ergonomic Handle Design with 30min Runtime & 6-in-1 Nozzle",
    "category": "汽车与摩托车 / 洗车及保养 / 水枪和雪沫喷枪",
    "price": "$33.98",
    "image": "assets/products/021.webp",
    "short_name": "SEESE Cordless Pressure Washer Gun",
    "category_en": "Car Wash Guns & Foamers",
    "visual_features": "Handheld cordless pressure washer gun in neon yellow-green and black, shown with a black hard case, black coiled hose, rechargeable battery, charger, and foam dispenser bottle.",
    "profile": "tech",
    "sheet": 4,
    "cell": 0,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 22,
    "id": "1732329137764667781",
    "name": "[VT COSMETICS] #1 viral PDRN Reedle Shot Hair Brush Serum with Original Liquid Microneedling & PDRN | Large-Capacity Full Scalp Care, Hair Thickening, Fuller-Looking Hair & Daily Root Care | Hairline, Roots, Baby Hair & Dry Scalp | Korean Haircare",
    "category": "美妆个护 / 头部护理与造型 / 头发与头皮养护",
    "price": "$19.89",
    "image": "assets/products/022.webp",
    "short_name": "VT Cosmetics PDRN Reedle Shot Hair Serum",
    "category_en": "Hair & Scalp Treatments",
    "visual_features": "Silver foil pouch with black lettering fitted with a wide turquoise comb-style applicator nozzle, presented against a pale blue gradient background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 12,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 23,
    "id": "1729508370969629931",
    "name": "[medicube] PDRN Pink Collagen Volume Multi Balm | All In One Volufiline, PDRN, NAD Stick for Youthful-Looking, Helping Look of Fine Lines, Firming Care, Anti-Aging Care | For Under-Eyes, Neck, Forehead, Smile Lines, Lip Care | Korean Skincare",
    "category": "美妆个护 / 美容护肤 / 面部护理套装",
    "price": "$21.00",
    "image": "assets/products/023.webp",
    "short_name": "Medicube PDRN Pink Collagen Multi Balm",
    "category_en": "Facial Care Sets",
    "visual_features": "Light pink cylindrical twist-up stick container open to show the pale pink balm core, positioned over a pink balm smudge on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 13,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 24,
    "id": "1731572915654201371",
    "name": "[Dr.Melaxin Official] Peel Shot Keratin Care Kojic Acid Turmeric Spray 200ml Pore Clearing Exfoliating Formula Skin Repair Scrub",
    "category": "美妆个护 / 洗浴与身体护理 / 身体磨砂膏、去角质",
    "price": "$25.11",
    "image": "assets/products/024.webp",
    "short_name": "Dr.Melaxin Peel Shot Turmeric Spray",
    "category_en": "Body Scrubs & Exfoliants",
    "visual_features": "Translucent amber cylindrical spray bottle fitted with an amber trigger sprayer and a white-and-orange striped label, positioned against a light beige circular backdrop.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 14,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 25,
    "id": "1732293553906094315",
    "name": "[medicube] NAD+ EGF Firming Serum | NAD+, EGF, Collagen Extract, Anti-aging, Plumping, Radiance Boosting Serum | Cares for Look of Fine Lines, Skin Elasticity & Firmness For Youthful-looking Skin (30ml / 1.01 fl. oz.) | Korean Skincare, K-Beauty",
    "category": "美妆个护 / 美容护肤 / 面部精华液",
    "price": "$23.00",
    "image": "assets/products/025.webp",
    "short_name": "Medicube NAD+ EGF Firming Serum",
    "category_en": "Facial Serums",
    "visual_features": "Deep red glass dropper bottle with a white bulb pipette cap, displayed on a white background with a textured red serum smear and small fluid drops.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 15,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 26,
    "id": "1731284232420626805",
    "name": "ADDWIN 2026 New Fascia Ring R10 Mini Muscle Recovery Fascia Device upgraded adjustable strap fits Up to 55in waist, Cordless Rechargeable, Designed for Waist & Back Muscle Recovery portable massager parents gift summervibes",
    "category": "运动与户外 / 健身设备 / 健身仪器",
    "price": "$22.99",
    "image": "assets/products/026.webp",
    "short_name": "ADDWIN Fascia Ring R10 Waist Device",
    "category_en": "Sports & Outdoors / Fitness Equipment / Fitness Devices",
    "visual_features": "Three models wearing wide gray adjustable belts with center-mounted modules; bottom insets display a black textured oval ring unit and a rolled gray fabric strap on a plain white background.",
    "profile": "active",
    "sheet": 2,
    "cell": 2,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 27,
    "id": "1732453804955177191",
    "name": "Women's Vintage Casual Street Style Loose Fit Baggy Pants, Elastic Waist Wide Leg Trousers, Retro Fashion Bottoms for Daily Wear",
    "category": "女装与女士内衣 / 女士下装 / 女士裤子",
    "price": "$16.81",
    "image": "assets/products/027.webp",
    "short_name": "Loose Fit Baggy Wide Leg Pants",
    "category_en": "Women's Clothing / Women's Bottoms / Women's Pants",
    "visual_features": "Person wearing loose-fitting, oversized black wide-leg trousers and light sneakers against a plain studio background, with a vertical column of circular color swatches on the right labeled 'MORE COLORS'.",
    "profile": "style",
    "sheet": 1,
    "cell": 5,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 28,
    "id": "1731887330794378206",
    "name": "【Gold-Color zipper】Soft Brushed Women's Sporty Jacket, 25'' Inseam Leggings. Gold-Color zipper Jacket with Pockets, Yoga Pants, Thumbholes Design, Casual Wear for Women Sweat Suit Active Dresse Set Try it,travel essentials,camping essentials tiktokshopbac",
    "category": "运动与户外 / 运动服饰 / 运动套装",
    "price": "$11.88",
    "image": "assets/products/028.webp",
    "short_name": "Women's Sporty Jacket and Leggings Set",
    "category_en": "Sports & Outdoors / Sportswear / Athletic Sets",
    "visual_features": "Model wearing a bright hot-pink long-sleeve athletic top and matching full-length leggings against an off-white background, with left-side infographic text and two thumbnail insets of the garments.",
    "profile": "active",
    "sheet": 2,
    "cell": 3,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 29,
    "id": "1729612709100426165",
    "name": "Loaded Water-Viral – Single Packet | 32oz Sugar Free Caffeinated Flavored Powder Beverage Mix | Made in USA | Easy to Mix",
    "category": "食品饮料 / 饮料 / 冲调饮品",
    "price": "$1.40",
    "image": "assets/products/029.webp",
    "short_name": "Loaded Water Powder Beverage Mix",
    "category_en": "Food & Beverages / Beverages / Drink Mixes",
    "visual_features": "Promotional infographic image displaying a person in a hot-pink long-sleeve athletic jumpsuit/two-piece set against a light background, with graphic text and thumbnail previews on the left.",
    "profile": "active",
    "sheet": 2,
    "cell": 4,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 30,
    "id": "1731200101340581930",
    "name": "Brightening Body Wash with Vitamin C & Glycolic Acid - 8fl oz | Helps even out skin tone",
    "category": "美妆个护 / 洗浴与身体护理 / 沐浴露与香皂",
    "price": "$10.49",
    "image": "assets/products/030.webp",
    "short_name": "Brightening Body Wash 8 fl oz",
    "category_en": "Beauty & Personal Care / Bath & Body / Body Wash",
    "visual_features": "Rectangular white plastic bottle with a bright yellow flip cap and yellow product label, standing on a white pedestal against a vibrant two-tone blue and magenta background with curved decorative pillars.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 16,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 31,
    "id": "1730936224134435123",
    "name": "OEAK Jelly Bras Women Seamless Lift Bra Wireless Push Up No Underwire Full Coverage Plus Bras Comfort Supportive Sports T-Shirt Bra",
    "category": "女装与女士内衣 / 女士内衣 / 女士文胸",
    "price": "$16.99",
    "image": "assets/products/031.webp",
    "short_name": "OEAK Seamless Wireless Bra",
    "category_en": "Women's Underwear & Sleepwear / Bras",
    "visual_features": "Two models showcasing seamless wireless bras; one in beige viewed from the front, and one in forest green showing the scoop back and matching bottoms, against a plain white studio background.",
    "profile": "style",
    "sheet": 1,
    "cell": 6,
    "confidence": 0.95,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 32,
    "id": "1729415062788019186",
    "name": "Physician's Choice Digestive Enzymes - Bloating & Mealtime Discomfort Support with Probiotics + Prebiotics for Digestion & Gut Health",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$15.97",
    "image": "assets/products/032.webp",
    "short_name": "Physician's Choice Digestive Enzymes",
    "category_en": "Health & Wellness / Dietary Supplements",
    "visual_features": "White plastic supplement bottle with a white screw cap and pink-and-white label, shown next to a small clear glass container against a vivid magenta-red backdrop with circular graphic badges.",
    "profile": "active",
    "sheet": 2,
    "cell": 5,
    "confidence": 0.89,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 33,
    "id": "1732352660592628585",
    "name": "(KakaPeople Easy-Off Bodysuit) Tummy Control Butt Lifter Faja Bodysuit, Back Support Scrunch Back Open Design, Postpartum Recovery Full Body Shaper with Cotton Gusset, Colombian Fajas Everyday Wear for Women",
    "category": "女装与女士内衣 / 女士内衣 / 女士塑身衣",
    "price": "$26.80",
    "image": "assets/products/033.webp",
    "short_name": "KakaPeople Easy-Off Bodysuit",
    "category_en": "Women's Underwear & Sleepwear / Shapewear",
    "visual_features": "Back angle of a model wearing black mid-thigh faja shapewear on a plain light background, with a circular inset highlighting the open drop-seat design.",
    "profile": "style",
    "sheet": 1,
    "cell": 7,
    "confidence": 0.98,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 34,
    "id": "1730278943412293794",
    "name": "CEELIKE Oral Spray, 20 mL, Freshens Breath, Available in Five Flavors",
    "category": "美妆个护 / 鼻子口腔护理 / 口腔喷剂",
    "price": "$10.65",
    "image": "assets/products/034.webp",
    "short_name": "CEELIKE Oral Spray",
    "category_en": "Beauty & Personal Care / Oral Care",
    "visual_features": "Graphic composition displaying a light blue and white oral spray bottle alongside lemon slices and a light blue information card over a soft blue background with bold overlaid text.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 17,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 35,
    "id": "1729413504705598306",
    "name": "360 Contour Lip Liner",
    "category": "美妆个护 / 美妆 / 眼线笔与唇线笔",
    "price": "$18.00",
    "image": "assets/products/035.webp",
    "short_name": "360 Contour Lip Liner",
    "category_en": "Beauty & Personal Care / Lip Liners",
    "visual_features": "Silver lip liner pencil with an uncapped metallic cap next to it, overlaid atop a textured swatch of nude-rose lip product on a light gray background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 18,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 36,
    "id": "1729619861328990466",
    "name": "Women's Solid Color Sports Leggings, Sporty Comfy Breathable Athletic Skinny Pants for Yoga Gym Workout Running, Ladies Sportswear for All Seasons, Gym Workout Bottoms",
    "category": "运动与户外 / 运动服饰 / 运动打底裤",
    "price": "$10.93",
    "image": "assets/products/036.webp",
    "short_name": "Solid Color Sports Leggings",
    "category_en": "Sports Leggings",
    "visual_features": "Full-length high-waisted leggings in olive brown worn with white athletic sneakers against a plain white background, with a gold circular icon at the top right.",
    "profile": "active",
    "sheet": 2,
    "cell": 6,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 37,
    "id": "1729532560217314285",
    "name": "Automatic Folding Umbrella, 1 Count/60pcs Portable Rain Umbrella with Loop Buckle, Windproof & Waterproof Umbrella for Men & Women",
    "category": "家居用品 / 家居日用 / 雨伞",
    "price": "$9.77",
    "image": "assets/products/037.webp",
    "short_name": "Folding Umbrella with Loop Buckle",
    "category_en": "Umbrellas",
    "visual_features": "Four folded compact umbrellas in black, navy blue, slate gray, and off-white hanging side-by-side on a rack, each equipped with an open carabiner-style ring handle.",
    "profile": "home",
    "sheet": 3,
    "cell": 1,
    "confidence": 0.89,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 38,
    "id": "1729504996201371033",
    "name": "Rosemary & Rice Water Hair Spray- 200ml Pack of 2",
    "category": "美妆个护 / 头部护理与造型 / 脱发产品",
    "price": "$15.99",
    "image": "assets/products/038.webp",
    "short_name": "Rosemary & Rice Water Hair Spray 2-Pack",
    "category_en": "Hair Treatment Products",
    "visual_features": "Two matching transparent cylindrical bottles filled with clear liquid, topped with black trigger spray nozzles and white labels with green and purple text against a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 19,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 39,
    "id": "1731580743505383759",
    "name": "PUTARE Wireless Induction Audio Speaker Stand, 5in1 Cellphone Holder, 3500mAh Rechargeable Emergency Power Bank,360° Adjustable Mobile Tablet Stand with Colorful Ambient Light Gifts for Men Women,",
    "category": "手机与数码 / 影音设备 / 音箱",
    "price": "$19.99",
    "image": "assets/products/039.webp",
    "short_name": "PUTARE Wireless Speaker Phone Stand",
    "category_en": "Speakers",
    "visual_features": "Dark gray angled desktop stand supporting a smartphone displaying a music player screen, featuring side dials, colorful edge lighting, and a charging cable on a wooden surface.",
    "profile": "tech",
    "sheet": 4,
    "cell": 1,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 40,
    "id": "1732265921298993534",
    "name": "[Vitafusion] Fiber Well Sugar Free Gummies - 5g - Berry & Peach Flavor Fiber Gummies - Supports Digestive Health & Regularity - 90 Gummies",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$13.99",
    "image": "assets/products/040.webp",
    "short_name": "Vitafusion Fiber Well Gummies",
    "category_en": "Dietary Supplements",
    "visual_features": "Gummy supplement bottle with blue and peach label branding, flanked by loose red, orange, and purple gummy pieces against a red background with circular callout graphics.",
    "profile": "active",
    "sheet": 2,
    "cell": 7,
    "confidence": 0.95,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 41,
    "id": "1729456803530772526",
    "name": "Toplux Keto Burn Supplement",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$16.46",
    "image": "assets/products/041.webp",
    "short_name": "Toplux Keto Burn Supplement",
    "category_en": "Dietary Supplements",
    "visual_features": "White plastic bottle with a ribbed screw cap, blue-to-purple gradient label with bold white lettering, placed in front of assorted fruits and leaves with capsules lying at the base.",
    "profile": "active",
    "sheet": 2,
    "cell": 8,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 42,
    "id": "1731006372333326477",
    "name": "NeoCell Collagen Peptides Powder 20oz - Grassfed Protein Supplement - Advanced with 18 Essential Amino Acids",
    "category": "保健 / 保健食品 / 美容保健食品",
    "price": "$29.99",
    "image": "assets/products/042.webp",
    "short_name": "NeoCell Collagen Peptides Powder",
    "category_en": "Collagen Supplements",
    "visual_features": "Muted slate-blue cylindrical plastic tub with a matching screw-on lid, featuring white brand lettering and an overlapping loops graphic on the front.",
    "profile": "active",
    "sheet": 2,
    "cell": 9,
    "confidence": 0.56,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 43,
    "id": "1732026353968975964",
    "name": "Rechargeable Shower Light No Wiring, 16 Color Changeable Ocean Wave Projector Light, Dimmable Waterproof Shower Lamp with Remote, Rotating Flame Water Ripple Lamp for Shower, Bathroom, Bedroom Decor,sohochic",
    "category": "家装建材 / 灯具和照明设备 / 新奇照明",
    "price": "$12.59",
    "image": "assets/products/043.webp",
    "short_name": "Ocean Wave Projector Light with Remote",
    "category_en": "Novelty Lighting",
    "visual_features": "Clear cubic projector light displaying blue ripple illumination, set alongside a white handheld remote in a tiled bathroom illuminated with blue wave patterns on walls and ceiling.",
    "profile": "home",
    "sheet": 3,
    "cell": 2,
    "confidence": 0.8,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 44,
    "id": "1732520820893519881",
    "name": "The Ordinary Lacto-PDRN* 4% + B9 Eye Cream",
    "category": "美妆个护 / 美容护肤 / 眼部护理",
    "price": "$9.50",
    "image": "assets/products/044.webp",
    "short_name": "The Ordinary Lacto-PDRN + B9 Eye Cream",
    "category_en": "Eye Creams",
    "visual_features": "White plastic squeeze tube with a pointed applicator cap set upright against textured smears of translucent off-white cream on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 0,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 45,
    "id": "1732294339991933438",
    "name": "DR.DENT Purple Mouthwash - Sachets 20 Pack - Peroxide-Free - Alcohol Free - Vegan Mint",
    "category": "美妆个护 / 鼻子口腔护理 / 漱口水",
    "price": "$16.47",
    "image": "assets/products/045.webp",
    "short_name": "DR.DENT Purple Mouthwash Sachets",
    "category_en": "Mouthwash",
    "visual_features": "Deep purple flip-top cardboard box open to reveal white-and-purple liquid stick sachets, with four sachets fanned out to the right against a violet gradient backdrop.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 1,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 46,
    "id": "1729553368065741562",
    "name": "HydroJug Traveler | Leak-Proof Insulated Tumbler with Flip Straw & Cup Holder Fit Flasks Lid Drinkware Leakproof Tumbler",
    "category": "厨房用品 / 饮具 / 保温杯",
    "price": "$25.49",
    "image": "assets/products/046.webp",
    "short_name": "HydroJug Traveler Insulated Tumbler",
    "category_en": "Kitchenware / Drinkware / Insulated Tumblers",
    "visual_features": "Black insulated travel tumbler with a narrow tapered bottom, large integrated side handle, and all-over celestial and mystical print, centered on a white background with 'Witchcraft' text at the top.",
    "profile": "home",
    "sheet": 3,
    "cell": 3,
    "confidence": 0.71,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 47,
    "id": "1729471510999109867",
    "name": "[medicube] Zero Pore Pads (AHA + BHA) |  Korean No.1 Viral Toner Pads",
    "category": "美妆个护 / 美容护肤 / 面部磨砂膏与去角质",
    "price": "$23.00",
    "image": "assets/products/047.webp",
    "short_name": "medicube Zero Pore Pads",
    "category_en": "Beauty & Personal Care / Skincare / Facial Exfoliators",
    "visual_features": "White cylindrical plastic jar featuring a vibrant blue screw cap and clean product labeling in black and blue text on a white circular-bordered background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 2,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 48,
    "id": "1729482835128784557",
    "name": "Magnesium Complex for Women, 240 Vegetarian Capsules | 20-in-1 Formula - Magnesium Blend with Vitamin D3, K2, Ashwagandha & More | Filler Free, Non-GMO",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$24.95",
    "image": "assets/products/048.webp",
    "short_name": "Magnesium Complex for Women Capsules",
    "category_en": "Health & Wellness / Dietary Supplements",
    "visual_features": "White plastic supplement bottle with a white ribbed cap and pink-accented label, displayed against a split purple and light pink background with three round feature icons on the side.",
    "profile": "active",
    "sheet": 2,
    "cell": 10,
    "confidence": 0.93,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 49,
    "id": "1732546842579407747",
    "name": "Comfrt | Signature Hoodie - Mega | Soft Comfy Roomy Everyday Essential Unisex Hoodie",
    "category": "女装与女士内衣 / 女士上装 / 女士卫衣",
    "price": "$39.00",
    "image": "assets/products/049.webp",
    "short_name": "Comfrt Signature Hoodie Mega",
    "category_en": "Women's Clothing / Tops / Hoodies & Sweatshirts",
    "visual_features": "Person wearing an oversized light pink hoodie with a drawstring hood and front pouch pocket, centered against a grey background flanked by circular white graphic callout badges.",
    "profile": "style",
    "sheet": 1,
    "cell": 8,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 50,
    "id": "1731879234948338174",
    "name": "DR.DENT Purple Teeth Whitening Strips - 7/21 Whitening Sessions - Peroxide-Free PAP Formula - Color-Correcting Purple",
    "category": "美妆个护 / 鼻子口腔护理 / 牙齿美白",
    "price": "$14.53",
    "image": "assets/products/050.webp",
    "short_name": "DR.DENT Purple Teeth Whitening Strips",
    "category_en": "Beauty & Personal Care / Oral Care / Teeth Whitening",
    "visual_features": "Purple rectangular box and matching single foil packet standing upright on a deep purple illuminated background with promotional white text displayed above.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 3,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 51,
    "id": "1729556031006938037",
    "name": "The Loaded Tea Shop - 40 Flavors, 1 Packet Makes 32 oz, Zero Sugar, Zero Carbs, Zero Calories, Zero Artificial Colors & Flavors, B-Complex, Vitamins D3 & K2, Aloe, 200mg Natural Caffeine, Build Your Own Bundle, Functional Energy Tea Packs",
    "category": "食品饮料 / 饮料 / 冲调饮品",
    "price": "$3.95",
    "image": "assets/products/051.webp",
    "short_name": "The Loaded Tea Shop Drink Mix Packs",
    "category_en": "Food & Beverage / Drink Mixes",
    "visual_features": "Row of colorful slim drink mix packets displayed with sliced fresh fruits and two large iced drinks in clear cups on a bright pink gradient background.",
    "profile": "active",
    "sheet": 2,
    "cell": 11,
    "confidence": 0.93,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 52,
    "id": "1732549643693888361",
    "name": "BISSELL HydrateWell™ Cat Water Fountain – Fresh, Filtered Water with Ultra-Quiet Wireless Pump",
    "category": "宠物用品 / 猫狗配件 / 喂养用具",
    "price": "$25.99",
    "image": "assets/products/052.webp",
    "short_name": "BISSELL HydrateWell Cat Water Fountain",
    "category_en": "Pet Supplies / Cat & Dog Feeders & Waterers",
    "visual_features": "An orange tabby cat drinking from a black round automatic pet fountain with a spout, set against a solid white background.",
    "profile": "home",
    "sheet": 3,
    "cell": 4,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 53,
    "id": "1732371632170307626",
    "name": "Gentle Exfoliating Body Wash and Brightening Boost Body Wash",
    "category": "美妆个护 / 洗浴与身体护理 / 沐浴露与香皂",
    "price": "$18.41",
    "image": "assets/products/053.webp",
    "short_name": "Gentle Exfoliating & Brightening Body Wash",
    "category_en": "Beauty & Personal Care / Body Wash",
    "visual_features": "Two rectangular white plastic bottles with yellow and orange screw caps positioned on a small wooden riser against a warm peach-colored background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 4,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 54,
    "id": "1731923439835452222",
    "name": "15-Day Fast-Acting Anti Cellulite  Sculpting & Tightening  Burn Gold Massage Cream |  Cryo Thermo cellulite remover for legs ,Belly & Arm|Refreshing Formula | Unisex Body Contouring Treatment for Men & Women |200 G #sohochic",
    "category": "美妆个护 / 洗浴与身体护理 / 身体霜、乳",
    "price": "$22.74",
    "image": "assets/products/054.webp",
    "short_name": "Burn Gold Anti-Cellulite Massage Cream",
    "category_en": "Beauty & Personal Care / Body Cream",
    "visual_features": "Clear round jar filled with swirling, textured golden gel-cream with a gold printed label on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 5,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 55,
    "id": "1731610554383569260",
    "name": "SHAPERX Shapewear for Women Tummy Control Bodysuits Zip-Up Comfort Ultra Stretch Fabric Customizable Fit Breathable Mesh Design Comfortable Fit",
    "category": "女装与女士内衣 / 女士内衣 / 女士塑身衣",
    "price": "$28.99",
    "image": "assets/products/055.webp",
    "short_name": "SHAPERX Women's Bodysuit Shapewear",
    "category_en": "Women's Clothing / Shapewear",
    "visual_features": "Black sleeveless, mid-thigh length one-piece shapewear bodysuit with thin adjustable straps, center front zipper, and sheer mesh panels on a plain background.",
    "profile": "style",
    "sheet": 1,
    "cell": 9,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 56,
    "id": "1732301660493680745",
    "name": "[Laka] [restock] Easy Glide Lip Liner — Creamy, Blendable Color with Smooth Application",
    "category": "美妆个护 / 美妆 / 口红与唇彩",
    "price": "$14.95",
    "image": "assets/products/056.webp",
    "short_name": "Laka Easy Glide Lip Liner",
    "category_en": "Beauty & Personal Care / Lip Liner",
    "visual_features": "Slender pink lip pencil uncapped next to its matching cap, showing drawn wavy swatch lines and a circular photo inset of lips in the upper right.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 6,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 57,
    "id": "1732404473502667708",
    "name": "tarte shape tape dab & go hair concealer",
    "category": "美妆个护 / 头部护理与造型 / 染发用品",
    "price": "$25.00",
    "image": "assets/products/057.webp",
    "short_name": "tarte dab & go hair concealer",
    "category_en": "Beauty & Personal Care / Hair Concealer",
    "visual_features": "Compact cylindrical rose-gold bottle with an exposed rounded dark brown sponge applicator tip on top against a white backdrop.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 7,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 58,
    "id": "1732376373883998234",
    "name": "YESNAP PeachPout Creatine for Women, 5g Creatine Monohydrate + 5g Collagen Powder, Myo-Inositol & BCAA, MACA, Hyaluronic Acid, Delicious Peach Flavor, 30 Packets, All-in-One Women Wellness Supplement",
    "category": "保健 / 保健食品 / 美容保健食品",
    "price": "$24.85",
    "image": "assets/products/058.webp",
    "short_name": "YESNAP PeachPout Creatine Supplement",
    "category_en": "Health & Wellness / Dietary Supplements",
    "visual_features": "Bright pink stand-up supplement pouch shown next to two pink stick packets, fresh peach slices, and a tall glass filled with pink drink.",
    "profile": "active",
    "sheet": 2,
    "cell": 12,
    "confidence": 0.9,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 59,
    "id": "1730227578434589155",
    "name": "Caramela Beauty Cyperus Rotundus Oil - 60ml/2oz Naturally Derived Gentle Moisturizing Hair Inhibitor, Body & Massage Oil for Sensitive Skin, Waxing Aftercare, Strawberry Skin Fix, Smooth Silky Beauty Products, Daily",
    "category": "美妆个护 / 洗浴与身体护理 / 保湿油、按摩油",
    "price": "$24.24",
    "image": "assets/products/059.webp",
    "short_name": "Caramela Beauty Cyperus Rotundus Oil",
    "category_en": "Beauty & Personal Care / Body & Massage Oil",
    "visual_features": "Amber glass dropper bottle with a white dropper top and pink label, placed in front of its matching colorful cardboard box.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 8,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 60,
    "id": "1732433811717395280",
    "name": "SOPAMI 360° Rotating Gap Cleaning Tool - Extendable Adjustable No-Touch Cleaner for Windows, Sliding Doors, Narrow Spaces, Home Deep Cleaning",
    "category": "家居用品 / 家庭护理用品 / 扫把",
    "price": "$13.99",
    "image": "assets/products/060.webp",
    "short_name": "SOPAMI 360° Rotating Gap Cleaning Tool",
    "category_en": "Home & Living / Cleaning Tools",
    "visual_features": "Dusty-pink mechanical pencil with separated cap, wavy swatch lines, brand text 'Laka', and a round portrait cutout in the upper right corner.",
    "profile": "home",
    "sheet": 3,
    "cell": 5,
    "confidence": 0.98,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 61,
    "id": "1732400886335181330",
    "name": "Striped V-Neck Wrap Top, Form-Fitting Puff Sleeve Y2K Crop Blouse, Stylish, Comfortable and Fashion Piece for Everyday Wear, Casual Everyday Tops",
    "category": "女装与女士内衣 / 女士上装 / 女士短袖",
    "price": "$4.69",
    "image": "assets/products/061.webp",
    "short_name": "Striped V-Neck Puff Sleeve Crop Top",
    "category_en": "Women's Clothing / Tops",
    "visual_features": "Model wearing a black and white horizontally striped deep V-neck crop top with short puff sleeves and dark jeans, alongside vertical color swatches.",
    "profile": "style",
    "sheet": 1,
    "cell": 10,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 62,
    "id": "1729456281219469588",
    "name": "Wellah Nutrition Creatine Monohydrate | 50 Servings | 3g Creatine | Supports Energy, Muscle Recovery & Strength, Cognitive Health Dietary Supplement Powder",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$15.95",
    "image": "assets/products/062.webp",
    "short_name": "Wellah Nutrition Creatine Monohydrate",
    "category_en": "Health & Wellness / Dietary Supplements",
    "visual_features": "White supplement tub with a colorful label featuring 'creatine' typography, fruit graphics, and a pink background with red side icons.",
    "profile": "active",
    "sheet": 2,
    "cell": 13,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 63,
    "id": "1730996878429623291",
    "name": "【Best Choice】Cofier High Quality Eyelashes Clusters Kit, Jelly-Coated Self-Adhesive Cluster Lashes with Tweezers, Easy Application, Beginner-Friendly Dramatic False Eyelashes & Adhesives (80/90/100 Pcs)",
    "category": "美妆个护 / 美妆 / 假睫毛与胶水",
    "price": "$22.99",
    "image": "assets/products/063.webp",
    "short_name": "Cofier Eyelashes Clusters Kit",
    "category_en": "Beauty & Personal Care / False Eyelashes",
    "visual_features": "Open black mirrored compact case containing multiple rows of segmented eyelash clusters, accompanied by black applicator tweezers on a white surface.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 9,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 64,
    "id": "1731093922834256103",
    "name": "Women's Solid Color Wide Leg Pants, Elegant Fashion Casual Trousers for Work Office Business, Ladies Bottoms for All Seasons",
    "category": "女装与女士内衣 / 女士下装 / 女士裤子",
    "price": "$16.78",
    "image": "assets/products/064.webp",
    "short_name": "Solid Color Wide Leg Pants",
    "category_en": "Women's Clothing / Pants",
    "visual_features": "Model standing wearing dark brown loose wide-leg trousers, with a vertical column of multi-colored round swatch options displayed on the right.",
    "profile": "style",
    "sheet": 1,
    "cell": 11,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 65,
    "id": "1731494787917189767",
    "name": "LeeFar Cutting Drink Mix | 30 Servings",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$16.99",
    "image": "assets/products/065.webp",
    "short_name": "LeeFar Cutting Drink Mix",
    "category_en": "Health & Wellness / Dietary Supplements",
    "visual_features": "Cylindrical yellow-to-pink gradient canister holding yellow stick packets inside, next to an open matching yellow lid on a white background.",
    "profile": "active",
    "sheet": 2,
    "cell": 14,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 66,
    "id": "1730369516036526190",
    "name": "All Purpose Scented Cleaner",
    "category": "家居用品 / 家庭护理用品 / 家用清洁剂",
    "price": "$17.96",
    "image": "assets/products/066.webp",
    "short_name": "All Purpose Scented Cleaner",
    "category_en": "Home & Living / Cleaning Supplies",
    "visual_features": "Brown plastic spray bottle with a white trigger sprayer and an off-white rectangular label on a plain white studio background.",
    "profile": "home",
    "sheet": 3,
    "cell": 6,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 67,
    "id": "1732589344831935216",
    "name": "Christmas Mini Squishies Advent Calendar 2026, 24-Day Dumpling Squishy Toy Countdown Calendar with Glitter Squeeze Toys, Holiday Gift for Kids",
    "category": "玩具和爱好 / 传统与创新玩具 / 史莱姆类玩具",
    "price": "$17.99",
    "image": "assets/products/067.webp",
    "short_name": "Christmas Squishy Advent Calendar",
    "category_en": "Toys & Hobbies / Squishy Toys",
    "visual_features": "Festive red advent calendar box with punch-out compartments, held by hands in front of a softly lit holiday background with small squishy figures.",
    "profile": "home",
    "sheet": 3,
    "cell": 7,
    "confidence": 0.88,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 68,
    "id": "1729387696935768412",
    "name": "Women's Plain Scoop Neck Sweater, Casual Drop Shoulder Long Sleeve Jumper, Women Fall & Winter Knit Top",
    "category": "女装与女士内衣 / 女士上装 / 女士毛衣与针织衫",
    "price": "$10.61",
    "image": "assets/products/068.webp",
    "short_name": "Plain Scoop Neck Drop Shoulder Sweater",
    "category_en": "Women's Clothing / Sweaters",
    "visual_features": "Off-white knit scoop-neck long-sleeve sweater laid flat above a grid of small circular color options on a plain white background.",
    "profile": "style",
    "sheet": 1,
    "cell": 12,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 69,
    "id": "1732403113516372924",
    "name": "tarte CC color-correcting tinted serum",
    "category": "美妆个护 / 美容护肤 / 面部精华液",
    "price": "$42.00",
    "image": "assets/products/069.webp",
    "short_name": "tarte CC Color-Correcting Tinted Serum",
    "category_en": "Beauty & Personal Care / Facial Serums",
    "visual_features": "Upright cylindrical pale beige cosmetic container featuring a light metallic rose-gold base band on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 10,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 70,
    "id": "1729714461980332262",
    "name": "OEAK Womens Jelly Bras Wireless Comfortable Soft Push Up Bralettes Seamless Tshirts Bras Deep V Everyday Bras",
    "category": "女装与女士内衣 / 女士内衣 / 女士文胸",
    "price": "$6.92",
    "image": "assets/products/070.webp",
    "short_name": "OEAK Women's Wireless Push Up Bralette",
    "category_en": "Women's Clothing & Underwear / Bras",
    "visual_features": "Two models side-by-side against a white background, one wearing a black plunge bralette and the other wearing a soft pink lace bralette.",
    "profile": "style",
    "sheet": 1,
    "cell": 13,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 71,
    "id": "1731626958257754665",
    "name": "PHOFAY Bikini Pain-Free Hair removal spray  for Sensitive Skin，Hypoallergenic Formula -Gentle & Fast-Acting Hair removal spray，Ginseng、Aloe & Hyaluronic Acid for Soothing Care,Suitable for Men & Women,backtoschool",
    "category": "美妆个护 / 洗浴与身体护理 / 除毛乳、除毛蜜蜡&除毛器",
    "price": "$16.99",
    "image": "assets/products/071.webp",
    "short_name": "PHOFAY Hair Removal Spray & Cream",
    "category_en": "Beauty & Personal Care / Hair Removal",
    "visual_features": "White and purple spray bottle standing next to a squeeze tube, decorated with aloe vera, sliced roots, and purple flowers on a white surface.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 11,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 72,
    "id": "1732497323004826110",
    "name": "DR.DENT Purple Toothpaste Tablets with 10% Hydroxyapatite & PAP | Fluoride-Free, SLS-Free, Vegan | Purple Tone-Correcting Formula | 90 Chewable Tablets per Tin",
    "category": "美妆个护 / 鼻子口腔护理 / 牙膏",
    "price": "$17.99",
    "image": "assets/products/072.webp",
    "short_name": "DR.DENT Purple Toothpaste Tablets",
    "category_en": "Beauty & Personal Care / Toothpaste",
    "visual_features": "White metal tin with bold purple branding, surrounded by several small purple chewable tablets on a clean white surface.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 12,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 73,
    "id": "1730986220018765913",
    "name": "Be Bodywise Advanced Hair Density Roll-On Serum 25 ml | 5% Saw Palmetto, 3% Rosemary, 1% Caffeine Herbasome & 3% Fenugreek | Scalp Serum for Reduced Hair Fall | Men & Women",
    "category": "美妆个护 / 头部护理与造型 / 脱发产品",
    "price": "$26.99",
    "image": "assets/products/073.webp",
    "short_name": "Be Bodywise Hair Density Roll-On Serum",
    "category_en": "Beauty & Personal Care / Scalp Care",
    "visual_features": "Slender white and blue roll-on applicator pen with transparent rollerball head, flanked by herb illustrations and text blocks on a white backdrop.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 13,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 74,
    "id": "1729619517262303653",
    "name": "[YCZ] Midnight Marine Eau de Parfum 1.7 fl oz Men's Fragrance - Aromatic Marine Scent, Magnetic, Sensual, Long-Lasting, Ideal for Dates & Everyday Wear, Gifts for Boyfriend, Anniversary Gift for Him, Men's Perfumes & Fragrances, Mens Gifts",
    "category": "美妆个护 / 香水 / 男士香水",
    "price": "$15.96",
    "image": "assets/products/074.webp",
    "short_name": "YCZ Midnight Marine Eau de Parfum",
    "category_en": "Beauty & Personal Care / Men's Fragrances",
    "visual_features": "Square dark blue glass perfume bottle with a cylindrical black cap and white printed lettering, casting a shadow on a white surface.",
    "profile": "style",
    "sheet": 1,
    "cell": 14,
    "confidence": 0.93,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 75,
    "id": "1732544791635398683",
    "name": "[Dr.Melaxin Official] Zero-Fit Blemish & Dark Spot Patch Duo 72 Patches × 2 | S-ZINC + Mela-C·E Ultra Thin Spot Patches with Salicylic Acid, Acne Care, Sulfur, Vitamin C & Niacinamide",
    "category": "美妆个护 / 美容护肤 / 痘痘、粉刺护理",
    "price": "$17.10",
    "image": "assets/products/075.webp",
    "short_name": "Dr.Melaxin Spot Patch Duo",
    "category_en": "Beauty & Personal Care / Acne & Blemish Treatments",
    "visual_features": "Two upright blister packs (one green, one orange) shown behind two transparent sheets holding circular adhesive spot patches against a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 14,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 76,
    "id": "1732466627757248608",
    "name": "Cheese Cube Squishy Toy - Yellow, Pink, Red & Green, Soft Moldable Petroleum Jelly-Filled Squeeze Ball, 6cm/7cm Squishy Fidgets ASMR Stress Relief Toy for Ages 12+, Unisex Anxiety Relief Sensory Toy",
    "category": "玩具和爱好 / 传统与创新玩具 / 减压玩具",
    "price": "$12.41",
    "image": "assets/products/076.webp",
    "short_name": "Cheese Cube Squishy Toy",
    "category_en": "Toys & Hobbies / Novelty Toys / Squeeze Toys",
    "visual_features": "Square and round textured squishy toys resting on a light round tray with hands pressing into the surface, accompanied by red and pink cube squishies in the background.",
    "profile": "home",
    "sheet": 3,
    "cell": 8,
    "confidence": 0.57,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 77,
    "id": "1732205382431839167",
    "name": "Car Phone Holder - 360-Degree Rotatable Adjustable Holder, Suction Cup Fixed Non-Slip, Horizontal/Vertical Angle Adjustment, Car Accessory for Dashboard Navigation, Fit for iPhone & Android Auto, Vehicle & Phone & Auto Accessories",
    "category": "汽车与摩托车 / 内部配件 / 车载支架",
    "price": "$10.99",
    "image": "assets/products/077.webp",
    "short_name": "Car Phone Holder",
    "category_en": "Automobiles & Motorcycles / Interior Accessories / Car Phone Mounts",
    "visual_features": "Black and metallic adjustable car mount base attached to a flat dashboard surface, set against a gradient blue studio backdrop with promotional text above.",
    "profile": "tech",
    "sheet": 4,
    "cell": 2,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 78,
    "id": "1729438652706624272",
    "name": "[Recommended by Kim Kardashian] Hismile V34 Colour Corrector - Tooth Stain Concealer, Temporary Brightening Booster, Purple Toothpaste, Colour Correcting",
    "category": "美妆个护 / 鼻子口腔护理 / 牙齿美白",
    "price": "$14.99",
    "image": "assets/products/078.webp",
    "short_name": "Hismile V34 Colour Corrector",
    "category_en": "Beauty & Personal Care / Oral Care / Teeth Whitening",
    "visual_features": "Deep purple rectangular cardboard box alongside a transparent pump bottle showing vivid purple gel inside, with a circular photo badge displayed on the left.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 15,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 79,
    "id": "1732609126661132353",
    "name": "Adjustable Tension Curtain Rod, No-Drill Telescoping Spring Pole for Bathroom, Closet and Inside Window Frame, Expandable,sohochic",
    "category": "家居用品 / 浴室用品 / 浴帘与浴帘杆",
    "price": "$9.99",
    "image": "assets/products/079.webp",
    "short_name": "sohochic Tension Curtain Rod",
    "category_en": "Home Supplies / Bathroom Accessories / Shower Curtain Rods",
    "visual_features": "Four collared shirts hanging on wooden hangers inside a white closet interior, with a circular inset graphic displaying a white telescoping tension rod.",
    "profile": "home",
    "sheet": 3,
    "cell": 9,
    "confidence": 0.96,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 80,
    "id": "1729579293681291410",
    "name": "Diffuser Oil by R&W Co.",
    "category": "家居用品 / 家庭护理用品 / 家居香薰",
    "price": "$30.59",
    "image": "assets/products/080.webp",
    "short_name": "R&W Co. Diffuser Oil",
    "category_en": "Home Supplies / Home Care / Home Fragrance",
    "visual_features": "Clear cylindrical bottle containing light yellow liquid, labeled with an amber-hued printed graphic label and sealed with a white screw cap on a white background.",
    "profile": "home",
    "sheet": 3,
    "cell": 10,
    "confidence": 0.94,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 81,
    "id": "1731997246433955867",
    "name": "[Dr.Melaxin Official] Gifted Collagen Boost Set Pore Spot Skin Care Calcium Collagen Volume Firming Balm for Enhanced Skin Health routine",
    "category": "美妆个护 / 美容护肤 / 面部护理套装",
    "price": "$55.80",
    "image": "assets/products/081.webp",
    "short_name": "Dr.Melaxin Collagen Boost Skincare Set",
    "category_en": "Facial Care Sets",
    "visual_features": "Five skincare containers lined up against a plain white background, including a small bottle with a pink cap, a clear dropper bottle, a wide cream jar with purple and white labeling, a smaller white jar with a purple lid, and a slim magenta tube.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 16,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 82,
    "id": "1732227985172828427",
    "name": "Women's Striped/rhombus/leaf/dot Cloud Handbag, Clip Closure Crossbody Bag, Lightweight Foldable for Daily Use, Gifts for Friends and Valentine's Day",
    "category": "箱包 / 女包 / 女士手拿包&腕包",
    "price": "$5.45",
    "image": "assets/products/082.webp",
    "short_name": "Striped Cloud Handbag Crossbody Bag",
    "category_en": "Clutches & Wristlets",
    "visual_features": "Puffy cloud-shaped fabric clutch bag featuring wide vertical stripes in alternating olive green and bubblegum pink, positioned on a white reflective surface.",
    "profile": "style",
    "sheet": 1,
    "cell": 15,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 83,
    "id": "1730261669388521504",
    "name": "Double-Sided Contoured Neck Pillow, Supportive Memory Foam with Cooling Cover, Zoned Design, and Extra-Large Armrest for Side, Stomach, and Back Sleepers #GLOBAL PICKS",
    "category": "家纺布艺 / 床上用品 / 枕头和背垫",
    "price": "$23.97",
    "image": "assets/products/083.webp",
    "short_name": "Contoured Memory Foam Neck Pillow",
    "category_en": "Pillows & Bolsters",
    "visual_features": "Ergonomically contoured cervical pillow with a butterfly-wing design, dark gray fabric top, and white breathable mesh sides, shown standalone at top and with a person resting on it below against a plain background.",
    "profile": "home",
    "sheet": 3,
    "cell": 11,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 84,
    "id": "1729931833196778371",
    "name": "Comfrt | The Dreamer Blanket | Oversized, Cozy, Soft Warm Throw",
    "category": "家纺布艺 / 床上用品 / 毯子",
    "price": "$95.00",
    "image": "assets/products/084.webp",
    "short_name": "Comfrt The Dreamer Blanket",
    "category_en": "Blankets & Throws",
    "visual_features": "A person wrapped in an oversized, plush ombre fleece blanket transitioning from pale sky blue at the top to deep navy blue at the bottom, set against a neutral studio backdrop with two round badge overlays.",
    "profile": "home",
    "sheet": 3,
    "cell": 12,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 85,
    "id": "1729992615540134195",
    "name": "Dr.Flash Handheld Garment Steamer for Clothing, Portable Iron Steamer Combo Travel Steam Generators, 7 Modes with LED Display,  Fast Heating, 90° Swivel Handle, 1-Button Start, Travel Stuff, New Year Gift",
    "category": "家电 / 生活家电 / 挂烫机",
    "price": "$29.99",
    "image": "assets/products/085.webp",
    "short_name": "Dr.Flash Handheld Garment Steamer",
    "category_en": "Garment Steamers",
    "visual_features": "Metallic grey handheld garment steamer with vibrant magenta trim and soleplate, depicted from front and profile angles emitting white steam, alongside a clear water cup and resting pad on a white background.",
    "profile": "home",
    "sheet": 3,
    "cell": 13,
    "confidence": 0.72,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 86,
    "id": "1732596482179371198",
    "name": "Foldable Metal Magnetic Car Cell Phone Holder - 360° Rotating Dashboard Mount, Adjustable Angle & Height, Strong Hold, Compact Universal Hands-Free Stand, Magnetic Mobile Mount, Car Interior Accessories, Vehicle Accessory",
    "category": "汽车与摩托车 / 内部配件 / 车载支架",
    "price": "$10.99",
    "image": "assets/products/086.webp",
    "short_name": "Foldable Magnetic Car Phone Mount",
    "category_en": "Automotive & Motorcycles / Interior Accessories / Phone Mounts & Holders",
    "visual_features": "Dark gray metal folding car phone mount with a circular magnetic pad on an articulated dual-joint arm, shown both extended and folded flat on a textured car dashboard.",
    "profile": "tech",
    "sheet": 4,
    "cell": 3,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 87,
    "id": "1732534855764971527",
    "name": "Halloween Dumpling Stress Relief Toys, 1pcs/3pcs/6pcs/8pcs/12pcs with Steamer Storage Boxes,Slow‑rebound maltose squishy toys, ideal for Halloween party gifts, featuring grimace pumpkin and little devil designs，12pcs Mini Dumpling(5cm）",
    "category": "玩具和爱好 / 传统与创新玩具 / 减压玩具",
    "price": "$2.98",
    "image": "assets/products/087.webp",
    "short_name": "Halloween Dumpling Squishy Stress Toys",
    "category_en": "Toys & Hobbies / Novelty & Gag Toys / Squeeze & Stress Relief Toys",
    "visual_features": "Six dome-shaped squishy toys in green, purple, yellow, white, and red with Halloween face designs resting in black circular steamer bases, shown being squeezed by hands below against a white background.",
    "profile": "home",
    "sheet": 3,
    "cell": 14,
    "confidence": 0.74,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 88,
    "id": "1732477923578581997",
    "name": "Women's Fashion Retro Plaid Gingham Stand Collar Short Coat, Drawstring Design, Zipper Front, Perfect for Fall Winter Daily Holiday Outing",
    "category": "女装与女士内衣 / 女士上装 / 女士夹克与风衣",
    "price": "$25.00",
    "image": "assets/products/088.webp",
    "short_name": "Retro Plaid Stand Collar Short Coat",
    "category_en": "Women's Clothing / Tops / Jackets & Windbreakers",
    "visual_features": "Cropped brown plaid jacket featuring a stand collar, chest flap pocket, front zip closure, and drawstring toggle hem, displayed indoors on a hanger.",
    "profile": "style",
    "sheet": 1,
    "cell": 16,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 89,
    "id": "1729411801317150864",
    "name": "Carpe Antiperspirant Deodorant - Clinically Tested 100-Hour Sweat & Odor Control - Quick-Drying, Non-Greasy Deodorant for Men & Women - No Baking Soda or Parabens",
    "category": "美妆个护 / 洗浴与身体护理 / 身体除臭&防汗剂",
    "price": "$15.72",
    "image": "assets/products/089.webp",
    "short_name": "Carpe Antiperspirant Deodorant",
    "category_en": "Beauty & Personal Care / Bath & Body / Deodorants & Antiperspirants",
    "visual_features": "Bright orange plastic deodorant stick with vertical white branding and a blue label badge, standing on a light gray pedestal against a clear blue background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 17,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 90,
    "id": "1732046289708290457",
    "name": "Bare Anatomy Ultra Smoothing Hair Trio – Shampoo, Mask & Serum",
    "category": "美妆个护 / 头部护理与造型 / 洗发护发",
    "price": "$24.99",
    "image": "assets/products/090.webp",
    "short_name": "Bare Anatomy Hair Trio Set",
    "category_en": "Beauty & Personal Care / Hair Care & Styling / Hair Care Sets",
    "visual_features": "Set of three muted purple hair care packages including a tall cylindrical bottle, a smaller pump dispenser bottle, and a round jar with a white lid, on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 18,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 91,
    "id": "1732321182598533162",
    "name": "The Body Refining Combo - Brightening Body Wash 8fl oz, Exfoliating Body Wash 8fl oz & AHA Body Lotion 8fl oz | Gently Exfoliates, Helps Improve Skin Texture & Deeply Moisturizes",
    "category": "美妆个护 / 洗浴与身体护理 / 身体霜、乳",
    "price": "$24.99",
    "image": "assets/products/091.webp",
    "short_name": "The Body Refining Combo Body Care Set",
    "category_en": "Body Care Sets",
    "visual_features": "Three white rectangular bottles with orange and yellow caps and labels, arranged on light grey pedestals against a warm peach-to-white gradient background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 19,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 92,
    "id": "1729890372836496007",
    "name": "LEEFAR Her Juicy Feminine Probiotics Gummies- All in One Solution with Slippery Elm and Prebiotics&Lactobacillus Probiotic Blend for Women’s pH Balance and Dryness - Hawaiian Pineapple Gummies 60 Count probiotics women",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$12.89",
    "image": "assets/products/092.webp",
    "short_name": "LEEFAR Her Juicy Feminine Probiotics Gummies",
    "category_en": "Dietary Supplements",
    "visual_features": "Magenta cylindrical plastic jar with a matching screw top and yellow lower band, placed beside several yellow gummies on a plain white surface.",
    "profile": "active",
    "sheet": 2,
    "cell": 15,
    "confidence": 0.91,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 93,
    "id": "1729405850428937058",
    "name": "Wonderskin 1440 Longwear Eyeliner - Lightweight Waterproof Vegan Cruelty-Free 24 Hour TruGlide Technology Ultra-Creamy Soft-Glide Application",
    "category": "美妆个护 / 美妆 / 眼线笔与唇线笔",
    "price": "$18.00",
    "image": "assets/products/093.webp",
    "short_name": "Wonderskin 1440 Longwear Eyeliner",
    "category_en": "Eyeliner",
    "visual_features": "Silver pencil eyeliner with an exposed black tip, separate matching cap, and a thick wavy black drawn line swatch, accompanied by a light green circular graphic badge on a white background.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 0,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 94,
    "id": "1731290195231281426",
    "name": "Wireless Video Doorbell Camera - 1080P Smart Outdoor Security Gadget with AI Human Detection, Night Vision, Instant Alert, 2-Way Audio, 2.4G WiFi Only, Easy Installation, Rechargeable Battery, Cloud Storage",
    "category": "手机与数码 / 摄影摄像 / 监控摄像设备",
    "price": "$15.99",
    "image": "assets/products/094.webp",
    "short_name": "Wireless Video Doorbell Camera",
    "category_en": "Video Doorbells",
    "visual_features": "Black oval-shaped smart doorbell unit with a glossy upper camera section and a lower round button, shown beside hands holding a smartphone displaying an application interface against a white background.",
    "profile": "tech",
    "sheet": 4,
    "cell": 4,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 95,
    "id": "1729501992376178299",
    "name": "20-Herb Blend Soursop Gummies Non-GMO Supplement - Sea Moss, Moringa, Turmeric + Oregano, Black Seed Oil, Ashwagandha - Immune Support, Body Health - Vegan, Easy-Take Capsule Format - 60 Capsules",
    "category": "保健 / 保健食品 / 保健食品",
    "price": "$12.99",
    "image": "assets/products/095.webp",
    "short_name": "Soursop 20-Herb Blend Supplement Gummies",
    "category_en": "Herbal Supplements",
    "visual_features": "Clear plastic bottle with a white lid and dark green label, filled with green capsules/gummies, flanked by dynamic green splashes, sliced soursop fruit, foliage, turmeric pieces, and black seeds.",
    "profile": "active",
    "sheet": 2,
    "cell": 16,
    "confidence": 0.99,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 97,
    "id": "1732194455909667123",
    "name": "【Professional Grade】Dr.ville 8X Niacinamide Foaming Toothpaste, Charcoal Teeth Whitening, Teeth Stain Remover, Gentle Deep Cleansing, Bad Breath Prevention, Daily Oral Care, 100ml-A, 8x Whitening Foam",
    "category": "美妆个护 / 鼻子口腔护理 / 牙膏",
    "price": "$12.99",
    "image": "assets/products/097.webp",
    "short_name": "Dr.ville 8X Niacinamide Foaming Toothpaste",
    "category_en": "Toothpaste",
    "visual_features": "White cylindrical pump bottle and matching vertical rectangular paper box featuring blue and white gradient wave graphics, displayed beside digital promotional badges and icons.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 1,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 98,
    "id": "1732158972727562920",
    "name": "Luxury Thick Removable Couch Cover, 1 Count Soft Textured Seat Pad, Non-Slip Washable Universal Sofa Protector, Sectional Sofa Slipcovers, Pet-Friendly Modern Slipcover for Sectional, Loveseat and 3-Seater Couch #GLOBAL PICKS",
    "category": "家纺布艺 / 居家布艺 / 沙发套",
    "price": "$7.91",
    "image": "assets/products/098.webp",
    "short_name": "Luxury Thick Removable Couch Cover",
    "category_en": "Sofa Covers & Slipcovers",
    "visual_features": "Dark gray textured plush sofa seat pad with light beige fleece edging and brown logo patch shown draped on a modern couch, with small color swatch bubbles along the bottom.",
    "profile": "home",
    "sheet": 3,
    "cell": 15,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 99,
    "id": "1730612955451985947",
    "name": "[Dr.Melaxin Official] BP Spicule Plumping LIP Shot - Maxi | Lip Plumper Volumizing Non-Sticky Glossy Lip Volumizer | Korean Cosmetics",
    "category": "美妆个护 / 美妆 / 口红与唇彩",
    "price": "$13.50",
    "image": "assets/products/099.webp",
    "short_name": "Dr.Melaxin Spicule Plumping Lip Shot",
    "category_en": "Lip Gloss & Plumpers",
    "visual_features": "Slim cylindrical lip product tube with a reflective metallic silver cap and a white body accented by mint green text, set against a plain white background with an official brand badge.",
    "profile": "beauty",
    "sheet": 0,
    "cell": 2,
    "confidence": 1.0,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  },
  {
    "index": 100,
    "id": "1732596718861520984",
    "name": "Halloween Door Mat Outside Entrance - Festive 3D Visual Skull, Clown Horror Front Porch Rug for Home Decor",
    "category": "运动与户外 / 休闲与室外休闲设备 / 马术用品",
    "price": "$12.99",
    "image": "assets/products/100.webp",
    "short_name": "Halloween 3D Visual Horror Door Mat",
    "category_en": "Doormats & Outdoor Rugs",
    "visual_features": "Rectangular doormat printed with a 3D optical illusion of a deep square stone pit with a creature inside, placed on a tiled entryway porch bordered by carved pumpkins and lanterns.",
    "profile": "home",
    "sheet": 3,
    "cell": 16,
    "confidence": 0.62,
    "avatar_assignment": "Jev selects creator profile; an illustrative portrait is rotated within that profile."
  }
];
