import { sealVisualTrack } from '@hypit/hypit/composition';
import { browserProgram, hyperframesResourceUri } from '@hypit/hypit/hyperframes';
export type Message={id:string;sender:string;text:string;side:string;at:any;productImage:any;avatarImage:any};
export type ChatOptions={id:string;title:string;entranceFrames:number};
export function renderChat(timeline:any,canvas:any,window:any,font:any,pairs:Message[],options:ChatOptions){
 if(!pairs.length)throw new Error('At least one pair is required');
 const children:any[]=[];let order=0;
 const tx=(id:string,text:string,size:number)=>{children.push({id,kind:'text',parent:'scene',order:++order,text,fonts:font.faces,style:[{name:'font-size',value:size+'px'},{name:'line-height',value:1.25},{name:'color',value:'#302631'}]});return '{{'+id+'}}'};
 const data=pairs.map(p=>({product:hyperframesResourceUri(p.productImage.resource),avatar:hyperframesResourceUri(p.avatarImage.resource)}));
 const n=pairs.length,cols=Math.ceil(Math.sqrt(n*1.4)),rows=Math.ceil(n/cols);
 const html=`<div class="intro">${tx('intro','让商品，匹配 AI 数字达人',49)}</div><div class="brand">${tx('brand','Yeadon',22)}</div><div class="focus"><div class="product"><img/></div><div class="arrow">↔</div><div class="avatar"><img/></div></div><div class="matrix">${data.map((_,i)=>`<div class="tile"><img class="person" src="${data[i]!.avatar}"><img class="goods" src="${data[i]!.product}"></div>`).join('')}</div><div class="outro">${tx('outro','Jev × Hypit',44)}${tx('url',options.title,24)}</div>`;
 const css=`:scope{background:#faf5f8;overflow:hidden}.intro{position:absolute;inset:0;background:#faf5f8;z-index:5;display:flex;align-items:center;justify-content:center}.brand{position:absolute;top:28px;left:36px}.focus{position:absolute;left:35px;top:132px;width:665px;height:455px;display:flex;align-items:center;gap:15px}.product,.avatar{width:300px;height:420px;overflow:hidden;background:white;border:1px solid #ead8e2;border-radius:15px}.product img{width:100%;height:100%;object-fit:contain}.avatar img{width:100%;height:100%;object-fit:cover}.arrow{font-size:27px;color:#b95b8e}.matrix{position:absolute;left:745px;right:30px;top:145px;height:420px;display:grid;grid-template-columns:repeat(${cols},1fr);grid-template-rows:repeat(${rows},1fr);gap:4px}.tile{position:relative;overflow:hidden;border-radius:4px;background:#e8dce4}.person{width:100%;height:100%;object-fit:cover}.goods{position:absolute;right:3%;bottom:4%;width:36%;height:34%;object-fit:contain;background:white;border-radius:3px}.outro{position:absolute;inset:0;background:#faf5f8;z-index:4;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:28px;opacity:0}`;
 const setup=`const q=s=>root.querySelector(s),tiles=[...root.querySelectorAll('.tile')];return frame=>{const t=frame/30;const i=Math.min(data.pairs.length-1,Math.max(0,Math.floor((t-1)/.16))%data.pairs.length);q('.intro').style.display=t<1?'flex':'none';q('.focus .product img').src=data.pairs[i].product;q('.focus .avatar img').src=data.pairs[i].avatar;const full=t>=8;const matrix=q('.matrix');matrix.style.left=full?'0px':'745px';matrix.style.right=full?'0px':'30px';matrix.style.top=full?'0px':'145px';matrix.style.height=full?'720px':'420px';q('.focus').style.opacity=full?'0':'1';tiles.forEach((e,k)=>{e.style.opacity=t>1+k*6/data.pairs.length?'1':'.12';e.style.transform='scale('+(1+.035*Math.max(0,Math.sin(t*13-k*.4)))+')'});q('.outro').style.opacity=t>=data.duration-3?'1':'0';};`;
 const program=browserProgram({html,css,setup,data:{pairs:data,duration:(window.span.endFrameExclusive-window.span.startFrame)/30}},pairs.flatMap(p=>[p.productImage,p.avatarImage]));
 return sealVisualTrack({id:options.id,programSpaceId:timeline.id,visualIr:'hypit.visual-ir@1',presents:[{id:options.id,span:window.span,stacking:{order:0,tieBreak:options.id},elements:[{id:'scene',kind:'program',order:0,program,style:[{name:'position',value:'absolute'},{name:'inset',value:0},{name:'width',value:canvas.widthPx+'px'},{name:'height',value:canvas.heightPx+'px'}]},...children]}]});
}
