import { sealVisualTrack } from '@hypit/hypit/composition';
import { browserProgram, hyperframesResourceUri } from '@hypit/hypit/hyperframes';
import { products } from './content.js';
export type Message={id:string;sender:string;text:string;side:string;at:any};
export type ChatOptions={id:string;title:string;entranceFrames:number};
export function renderChat(timeline:any,canvas:any,window:any,font:any,messages:Message[],options:ChatOptions,assets:Record<string,any>){
 let order=0;const children:any[]=[];
 const tx=(id:string,text:string,size=22,color='#241c24')=>{children.push({id,kind:'text',parent:'scene',order:++order,text,fonts:font.faces,style:[{name:'font-size',value:size+'px'},{name:'line-height',value:1.2},{name:'color',value:color},{name:'white-space',value:'nowrap'}]});return '{{'+id+'}}'};
 const urls=Object.fromEntries(Object.entries(assets).map(([k,v])=>[k,hyperframesResourceUri(v.resource)]));
 const face=(p:any)=>`background-image:url('${urls['sheet'+p.sheet]}');background-size:400% 500%;background-position:${(p.cell%4)*100/3}% ${Math.floor(p.cell/4)*25}%`;
 const selected=[3,39,46,82].map(id=>products.find(p=>p.index===id)!);
 const clips=selected.map((_,i)=>{const start=(12+i*3)*30;children.push({id:'clip'+i,kind:'video',parent:'scene',order:++order,artifact:assets['clip'+i],muted:true,style:[{name:'position',value:'absolute'},{name:'inset',value:0},{name:'width',value:'100%'},{name:'height',value:'100%'},{name:'object-fit',value:'cover'}],sampling:{sourceFrameRate:{numerator:30,denominator:1},sourceFrameCount:300,segments:[{target:{startFrame:start,endFrameExclusive:start+90},sourceFrame:{numerator:[120,90,30,90][i]!,denominator:1},rate:{numerator:1,denominator:1}}]}});return `<div class="ugc-clip">{{clip${i}}}</div>`}).join('');
 const html=`<div class="paper"></div><section class="opening">${tx('opening','让商品，自动匹配 AI 数字达人',51)}</section><section class="console"><div class="product"><img></div><div class="portrait"></div><div class="arrow">→</div><div class="counter">${tx('counter','000',43)}${tx('total','/ 99',16)}</div><div class="matrix">${products.map((p,i)=>`<div class="slot"><div class="mini" style="${face(p)}"></div><div class="wash"></div></div>`).join('')}</div></section><section class="ugc"><div class="ugc-product"><img></div><div class="ugc-arrow">→</div><div class="ghosts">${selected.map(p=>`<div style="${face(p)}"></div>`).join('')}</div></section>${clips}<section class="wall">${products.map(p=>`<div class="tile"><div class="tile-face" style="${face(p)}"></div><img src="${urls['product'+p.index]}"></div>`).join('')}</section><section class="outro"><div>${tx('endbrand','Jev × Hypit',62)}</div><div>${tx('endurl','github.com/Yeadon8888/jev-hypit-commerce',27)}</div></section><div class="flash"></div>`;
 const css=`:scope{background:#faf3f6;overflow:hidden;font-family:sans-serif}.paper{position:absolute;inset:0;background:radial-gradient(ellipse at center,#fff,#f8eff4)}.opening{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;z-index:20}.console,.ugc{position:absolute;inset:0}.product{position:absolute;left:40px;top:124px;width:336px;height:474px;background:white;border:1px solid #e2d7df;border-radius:12px;overflow:hidden}.product img{width:100%;height:100%;padding:16px;box-sizing:border-box;object-fit:contain}.portrait{position:absolute;left:425px;top:124px;width:330px;height:474px;border-radius:10px;background-repeat:no-repeat;overflow:hidden}.arrow{position:absolute;left:765px;top:340px;color:#b97497;font-size:31px}.counter{position:absolute;left:805px;top:127px;display:flex;align-items:baseline;gap:8px}.matrix{position:absolute;left:805px;top:204px;width:437px;height:394px;display:grid;grid-template-columns:repeat(10,1fr);grid-template-rows:repeat(10,1fr);gap:3px}.slot{position:relative;background:#e9e1e7;border-radius:3px;overflow:hidden}.mini{position:absolute;left:0;top:-4px;width:43.7px;height:52.4px;background-repeat:no-repeat}.wash{position:absolute;inset:0;background:#e876b94a;opacity:0}.ugc-product{position:absolute;left:160px;top:126px;width:414px;height:468px;background:white;border:1px solid #e5d9e1;border-radius:16px;overflow:hidden}.ugc-product img{width:100%;height:100%;object-fit:contain;padding:18px;box-sizing:border-box}.ugc-arrow{position:absolute;left:627px;top:326px;font-size:42px;color:#bc7a9f}.ugc-clip{position:absolute;left:724px;top:95px;width:304px;height:540px;border-radius:17px;overflow:hidden;isolation:isolate;box-shadow:0 18px 50px #69445120;border:1px solid #ffffff99}.ghosts{position:absolute;inset:0;opacity:.12}.ghosts div{position:absolute;width:85px;height:102px;border-radius:7px;left:1120px;top:85px}.ghosts div:nth-child(2){top:220px;left:1110px}.ghosts div:nth-child(3){top:365px;left:1140px}.ghosts div:nth-child(4){top:510px;left:1100px}.wall{position:absolute;inset:0;perspective:1200px}.tile{position:absolute;overflow:hidden;border-radius:4px;background:#eddae5;border:1px solid #fff9}.tile-face{position:absolute;inset:0;background-repeat:no-repeat}.tile img{position:absolute;right:5%;bottom:5%;width:28%;height:28%;object-fit:contain;background:white;border-radius:4px}.outro{position:absolute;inset:0;display:flex;flex-direction:column;gap:29px;align-items:center;justify-content:center;background:radial-gradient(ellipse,#fff,#f8eff4)}.flash{position:absolute;inset:0;background:white;opacity:0;pointer-events:none;z-index:25}`;
 const setup=`const $=s=>root.querySelector(s),all=s=>Array.from(root.querySelectorAll(s)),clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>1-Math.pow(1-clamp(x),3),show=(el,on,display='block')=>el.style.display=on?display:'none';const mini=all('.mini'),clips=all('.ugc-clip'),tiles=all('.tile');let last=-1,lastU=-1;const face=(el,p)=>{el.style.backgroundImage='url('+data.urls['sheet'+p.sheet]+')';el.style.backgroundSize='400% 500%';el.style.backgroundPosition=(p.cell%4)*100/3+'% '+Math.floor(p.cell/4)*25+'%'};const counter=$('.counter').firstElementChild;let leaf=counter;while(leaf.firstElementChild)leaf=leaf.firstElementChild;return frame=>{const t=frame/30;show($('.opening'),t<1,'flex');$('.opening').style.opacity=String(ease(t/.18));show($('.console'),t>=1&&t<12);show($('.ugc'),t>=12&&t<24);show($('.wall'),t>=24&&t<27);show($('.outro'),t>=27,'flex');const count=Math.min(99,Math.max(0,Math.floor((t-1)*9.9)));const cur=Math.max(0,count-1);if(cur!==last){$('.product img').src=data.urls['product'+data.products[cur].index];face($('.portrait'),data.products[cur]);last=cur}leaf.textContent=String(count).padStart(3,'0');mini.forEach((el,i)=>{const age=t-(1+(i+1)/9.9);el.style.opacity=age>=0?'1':'0';el.style.transform='scale('+(age<0?0:1+.18*Math.exp(-age*11)*Math.sin(age*26))+')';el.nextElementSibling.style.opacity=t>11?String(Math.max(0,Math.sin((t-11)*12-i*.13))*.5):'0'});const n=Math.floor((t-12)/3);if(t>=12&&t<24&&n!==lastU){$('.ugc-product img').src=data.urls['product'+data.selected[n].index];lastU=n}clips.forEach((el,i)=>{show(el,t>=12+i*3&&t<15+i*3);el.style.transform='translateY('+(1-ease((t-12-i*3)/.25))*18+'px)'});all('.ghosts div').forEach((e,i)=>e.style.transform='rotate('+Math.sin(t+i)*5+'deg) translateY('+Math.sin(t*2+i)*8+'px)');if(t>=24&&t<27){const mode=t<24.8?12:t<25.6?36:99,cols=mode===12?4:mode===36?9:17,rows=Math.ceil(mode/cols);tiles.forEach((el,i)=>{show(el,i<mode);const w=1200/cols,h=560/rows,c=i%cols,r=Math.floor(i/cols);el.style.left=(40+c*w)+'px';el.style.top=(64+r*h)+'px';el.style.width=(w-4)+'px';el.style.height=(h-4)+'px';el.style.transform='scale('+(1+.022*Math.sin(t*14+c+r))+')';const portrait=el.firstElementChild;const fw=Math.max(w,h*256/307),fh=fw*307/256;portrait.style.width=fw+'px';portrait.style.height=fh+'px';portrait.style.left=(w-fw)/2+'px';portrait.style.top=-(fh-h)*.2+'px'})}$('.outro').style.opacity=String(ease((t-27)/.3));$('.flash').style.opacity=String(Math.max(0,...[12,15,18,21,24,24.8,25.6,27].map(c=>t>=c&&t<c+.1?.12*(1-(t-c)/.1):0)));};`;
 const program=browserProgram({html,css,setup,data:{urls,products,selected}},Object.values(assets));
 return sealVisualTrack({id:options.id,programSpaceId:timeline.id,visualIr:'hypit.visual-ir@1',presents:[{id:options.id,span:window.span,stacking:{order:0,tieBreak:options.id},elements:[{id:'scene',kind:'program',order:0,program,style:[{name:'position',value:'absolute'},{name:'inset',value:0},{name:'width',value:canvas.widthPx+'px'},{name:'height',value:canvas.heightPx+'px'}]},...children]}]});
}
